// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxXqROjzUNxUSOWCGyPhqfINfqt6kYlQ',
    appId: '1:49728211047:web:bc7406122493dbd7c22cc2',
    messagingSenderId: '49728211047',
    projectId: 'muntazir-201fc',
    authDomain: 'muntazir-201fc.firebaseapp.com',
    storageBucket: 'muntazir-201fc.firebasestorage.app',
    measurementId: 'G-K1S1ZHHR0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQvCVXpkWPqPvTP9CAPGCzZmJ-d1qsUU',
    appId: '1:49728211047:android:2be07170d96deeadc22cc2',
    messagingSenderId: '49728211047',
    projectId: 'muntazir-201fc',
    storageBucket: 'muntazir-201fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfNNCmDliD-CCh9jw_HX5Uev9KjriEKZA',
    appId: '1:49728211047:ios:61248b6a7eb4ffb6c22cc2',
    messagingSenderId: '49728211047',
    projectId: 'muntazir-201fc',
    storageBucket: 'muntazir-201fc.firebasestorage.app',
    iosBundleId: 'com.muntazir.muntazir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfNNCmDliD-CCh9jw_HX5Uev9KjriEKZA',
    appId: '1:49728211047:ios:61248b6a7eb4ffb6c22cc2',
    messagingSenderId: '49728211047',
    projectId: 'muntazir-201fc',
    storageBucket: 'muntazir-201fc.firebasestorage.app',
    iosBundleId: 'com.muntazir.muntazir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFxXqROjzUNxUSOWCGyPhqfINfqt6kYlQ',
    appId: '1:49728211047:web:485ae85373679f58c22cc2',
    messagingSenderId: '49728211047',
    projectId: 'muntazir-201fc',
    authDomain: 'muntazir-201fc.firebaseapp.com',
    storageBucket: 'muntazir-201fc.firebasestorage.app',
    measurementId: 'G-6JSXZRYRXT',
  );
}
